---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nufg4418/public_html/
    - /bin/cp -R .htaccess robots.txt sitemap.xml 404.html about.html en kelola-hj5o1d nge-employee-ob memo-storage article.html career.html contact.html faq.html gallery.html global.html index.html news-events.html program-english-camp.html program-english-course.html program-immersion.html program-immersion-australia.html program-immersion-malaysia.html program-immersion-turkey.html program-immersion-singapore.html program-native-speaker.html program-study-abroad.html program-teacher-training.html programs.html school-partnership.html script.js style.css testimonials.html assets $DEPLOYPATH
